language: cpp
compiler: gcc
install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake

script:
  - qmake qrealRobots.pro
  - make 
  - make distclean
  - qmake qrealTest.pro CONFIG+=debug
  - make 
  - ./bin/unittests/qrlibs_unittests

notifications:
  email:
    recipients:
      - qreal-build-reports@googlegroups.com
