language: cpp
compiler: gcc
install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake qt4-dev-tools

script:
  - cat /proc/cpuinfo

notifications:
  email:
    recipients:
      - qreal-build-reports@googlegroups.com
